### ISSUE TITLE
Flutter: Add dark mode in dev-bloc branch

### ISSUE THREAD

**Issue by skohan** [sohan-k/todo.github.io#1]
Add dark mode toggle on the upper right corner of the app and use Bloc architecture to implement it. Create pull request to the `dev-bloc` branch.

**Comment by abkoradiya** [comment]
Which version of bloc you are using? Because when I clone your code then it showing error in blocbuilder.

**Comment by skohan** [comment]
Actually, I have not specified any version in pubspec, which means it is using the latest one.

**Comment by abkoradiya** [comment]
I want to contribute this. Please assign it to me.

**Comment by abkoradiya** [comment]
At which place switch need to be added? Is appbar right place for that?

**Comment by skohan** [comment]
Add to the upper right corner of the app. Use bloc architecture for adding

**Comment by skohan** [comment]
Closed #2
